name: NorskeKommandoer
version: 1.1.2
description: Mange norske kommandoer.
author: nicholasblang
main: com.hotmail.langbach.nicholas.norskekommandoer.Main

commands:
  settspawn:
    description: Setter spawn punktet.
    usage: /<command>
  spawn:
    description: Teleporterer deg til spawn punktet.
    usage: /<command>
  fly:
    description: Setter deg i fly modus.
    usage: /<command>
    aliases: [svev]
  stuck:
    description: Teleporterer deg til den høyeste blokken.
    usage: /<command>
    aliases: [s, sitterfast, fast]
  location:
    description: Sender en melding om hva kordinatene dine er.
    usage: /<command> <spiller>
    aliases: [loc, kordinater, kor]
  openinv:
    description: Åpner spilleren som er angitt sitt invetory.
    usage: /<command> <spiller>
    aliases: [invsee, åpneinv]
  ping:
    description: Hviser pingen din eller pingen til spilleren du skrev.
    usage: /<command> <spiller>
  nk:
    description: Noen sub-kommandoer.
    usage: /<command>
    aliases: [norskekommandoer]
  spillerinfo:
    description: Gir informasjon om spilleren.
    usage: /<command> <spiller>
  tpa:
    description: Sender en TPA forespørsel til en spiller.
    usage: /<command> <spiller>
    aliases: [tpforespørsel, tpf]
  godta:
    description: Godtar en TPA forespørsel.
    usage: /<command> <spiller>
  avvis:
    description: Avviser en TPA forespørsel.
    usage: /<command> <spiller>
  stabsamtale:
    description: En privat samtale for alle stab medlemmer.
    usage: /<command>
    aliases: [ss, stabs, ssamtale]
  kick:
    description: Kicker en spiller.
    aliases: [spark, sparkut]
    usage: /<command> <spiller>
  pvp:
    description: Setter av eller på pvp.
    usage: /<command>
  stabhjelp:
    description: Sender en melding til stab medlemmene.
    usage: /<command> <melding>
    aliases: [shjelp, helpop, stabh, sh]
  rens:
    description: Renser ditt inventar.
    usage: /<command> [spiller]
    aliases: [ci, cleari, cinventory]
permissions:
  norskekommandoer.settspawn:
    description: Gir deg permission til å bruke kommandoen /settspawn.
    default: op
  norskekommandoer.stuck:
    description: Gir deg permission til å bruke kommandoen /stuck
    usage: /<command>
  norskekommandoer.fly:
    description: Gir deg permission til å bruke kommandoen /fly.
    default: op
  norskekommandoer.location:
    description: Gir deg permission til å bruke kommandoen /location.
    default: op
  norskekommandoer.openinv:
    description: Gir deg permission til å bruke kommandoen /openinv.
    default: op
  norskekommandoer.reload:
    description: Gir deg permission til å bruke kommandoen /norskekommandoer reload
    default: op
  norskekommandoer.spillerinfo:
    description: Gir deg permission til å bruke kommandoen /spillerinfo
    default: op
  norskekommandoer.tpa:
    description: Gir deg permission til å bruke /tpa, /avvis og /godta.
    default: op
  norskekommandoer.stab:
    description: Gir deg permission til stab kommandoer
    default: op
  norskekommandoer.kick:
    description: Gir deg permission til å bruke /kick
    default: op
  norskekommandoer.pvp:
    description: Gir deg permission til å bruke /pvp
    default: op
  norskekommandoer.rens:
    description: Gir deg permission til å bruke /rens
    default: op
  norskekommandoer.*:
    description: Gir deg alle permissionsene til pluginen NorskeKommandoer.
    children:
      norskekommandoer.settspawn: true
      norskekommandoer.fly: true
      norskekommandoer.stuck: true
      norskekommandoer.location: true
      norskekommandoer.openinv: true
      norskekommandoer.reload: true
      norskekommandoer.spillerinfo: true
      norskekommandoer.tpa: true
      norskekommandoer.stab: true
      norskekommandoer.kick: true
      norskekommandoer.pvp: true
      norskekommandoer.rens: true